name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1
        
#    - name: Show Environment
#      run: echo Current ref - ${{GITHUB.REF}}

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1
      
    - uses: rlespinasse/github-slug-action@master
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_HEAD_REF_SLUG }}
        echo ${{ env.GITHUB_BASE_REF_SLUG }}

    - name: Nuget Pack
      working-directory: .
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: nuget pack torteliniw.nuspec -version 1.0.0-dev -OutputFileNamesWithoutVersion -OutputDirectory dist
      
    - name: Nuget Pack/Push
      if: startsWith(github.ref, 'refs/tags/')
      working-directory: .
      run: |
        nuget pack torteliniw.nuspec -version ${{GITHUB_REF#refs/tags/}} -OutputFileNamesWithoutVersion -OutputDirectory dist
        nuget push dist\torteliniw.nupkg -ApiKey ${{secrets.nuget_api_key}} -Source https://api.nuget.org/v3/index.json