name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1
        
    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Pack
      working-directory: .
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: nuget pack torteliniw.nuspec -version 1.0.0-dev -OutputFileNamesWithoutVersion -OutputDirectory dist
      
    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      uses: olegtarasov/get-tag@v2
      id: tagName
      with:
        tagRegex: "([0-9\\.]+.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.

    - name: Nuget Pack/Push
      if: startsWith(github.ref, 'refs/tags/')
      working-directory: .
      run: |
        nuget pack torteliniw.nuspec -version $GIT_TAG_NAME -OutputFileNamesWithoutVersion -OutputDirectory dist
        nuget push dist\torteliniw.nupkg -ApiKey ${{secrets.nuget_api_key}} -Source https://api.nuget.org/v3/index.json