name: Test
on: [push]

jobs:
  buildlinux:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        run: |
          sudo apt install cmake
      - name: Configure
        run: |
          mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
      - name: Build
        run: |
          cmake --build build
      - name: Test
        run: |
          cd build && ctest -VV -- -ls
