name: Test
on: [push]

jobs:
  buildlinux:
    name: Test Linux
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make 
  buildmac:
    name: Test macOS
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make 
  buildwindows:
    name: Test Windows
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make 